name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      - uses: actions/checkout@v3

      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_RIVER_09B55501E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload

          # Angular
          app_location: myapp
          app_build_command: |
            npm install
            npm run build -- --configuration production
          output_location: dist/myapp/browser

          # Azure Functions
          api_location: api
          api_build_command: npm install
