name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [main]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # ---------- BUILD ANGULAR ----------
      - name: Install & Build Angular
        working-directory: myapp
        run: |
          npm ci
          npm run build -- --configuration production

      # ---------- BUILD API (FUNCTIONS) ----------
      - name: Install API dependencies
        working-directory: api
        run: |
          npm ci

      # ---------- DEPLOY (UPLOAD ONLY) ----------
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_RIVER_09B55501E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"

          # YA COMPILADO (no Oryx)
          app_location: "myapp/dist/myapp/browser"
          skip_app_build: true

          api_location: "api"
          skip_api_build: true
